apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: helloservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - helloservice.crossplane-perf-test.34.67.191.73.nip.io
  - helloservice
  http:
  - route:
    - destination:
        host: helloservice.crossplane-perf-test.svc.cluster.local
